version: "3.7"
services:
  db:
    image: postgres:14.4-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      -  ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: star_notary
